 # This file (Kbuild) was created by Ron Rechenmacher <ron@fnal.gov> on
 # Jan  3, 2013. "TERMS AND CONDITIONS" governing this file are in the README
 # or COPYING file. If you do not have such a file, one can be obtained by
 # contacting Ron or Fermi Lab in Batavia IL, 60510, phone: 630-840-3000.
 # $RCSfile: Kbuild,v $
 # rev="$Revision: 416 $$Date: 2015-10-13 11:48:10 -0500 (Tue, 13 Oct 2015) $";

obj-m := TRACE.o
#ccflags-y := -I$(src)/../include
TRACE-y := trace_.o

