
.TH "trace_cntl info" 1 "August 2018" "1.0" "User Commands"
.SH NAME
trace_cntl info, tinfo

.SH SYNOPSIS 
.br 
.B tinfo \fI[opt\fR]


.SH DESCRIPTION
Executing "tinfo" in this environment will create the memory buffer file (at /tmp/trace_buffer_USER) if doesn't exists, then display the info about the file.

.TP 20
.I tinfo
[opt] -- print info


.SH AUTHOR
Matthew Adas <madas@fnal.gov>
.PP
Ron Rechenmacher <ron@fnal.gov>


.SH SEE ALSO
.br
\fBtcntl\fR(1)
.br
\fBtmode\fR(1)
.br
\fBtshow\fR(1)
.br
\fBttids\fR(1)
.br
\fBtlvlM\fR(1)
.br
\fBtfreeze\fR(1)
.br
\fBtreset\fR(1)
.br
\fBtdelta\fR(1)
.br
\fBtenv\fR(1)
.br
\fBtonM\fR(1)
.br
\fBtoffM\fR(1)
.br
\fBtlvlsSave\fR(1)
.br
\fBtlvlsRestore\fR(1)


.\" tinfo()   { trace_cntl info "$@"; }


