
.TH "trace_cntl reset" 1 "August 2018" "1.0" "User Commands"
.SH NAME
trace_cntl reset, treset

.SH SYNOPSIS 
.br 
.B treset


.SH DESCRIPTION
.TP 20
.I \fBtreset\fR
-- clears the memory buffer and trigger parameters


.SH EXAMPLES
This redmine article contains some \fBtreset\fR usage and is titled \fBOS and compiler features used\fR:
.PP
https://cdcvs.fnal.gov/redmine/projects/trace/wiki/Does_it_work_and_how_does_it_work
.PP
This redmine article contains other uses:
.PP
https://cdcvs.fnal.gov/redmine/projects/trace/wiki/TRACE_Users_Guide

.SH AUTHOR
Matthew Adas <madas@fnal.gov>
.PP
Ron Rechenmacher <ron@fnal.gov>

.SH SEE ALSO
.br
\fBtcntl\fR(1)
.br
\fBtmode\fR(1)
.br
\fBtshow\fR(1)
.br
\fBtinfo\fR(1)
.br
\fBttids\fR(1)
.br
\fBtlvlM\fR(1)
.br
\fBtfreeze\fR(1)
.br
\fBtdelta\fR(1)
.br
\fBtenv\fR(1)
.br
\fBtonM\fR(1)
.br
\fBtoffM\fR(1)
.br
\fBtlvlsSave\fR(1)
.br
\fBtlvlsRestore\fR(1)



