 # This file (Makefile<script>) was created by Ron Rechenmacher <ron@fnal.gov> on
 # Feb 19, 2019. "TERMS AND CONDITIONS" governing this file are in the README
 # or COPYING file. If you do not have such a file, one can be obtained by
 # contacting Ron or Fermi Lab in Batavia IL, 60510, phone: 630-840-3000.
 # $RCSfile: .emacs.gnu,v $
 # rev="$Revision: 1.33 $$Date: 2019/01/13 02:34:40 $";


${OUT}% : %
	cp $< $@

all: ${OUT}bitN_to_mask ${OUT}trace_delta ${OUT}trace_addr2line ${OUT}trace_envvars ${OUT}trace_maxents ${OUT}trace_color ${OUT}trace-cmd-merge
	echo done with target all

