#!/bin/sh
# This file (trace-cmd-merge) was created by Ron Rechenmacher <ron@fnal.gov> on
# Apr 18, 2023. "TERMS AND CONDITIONS" governing this file are in the README
# or COPYING file. If you do not have such a file, one can be obtained by
# contacting Ron or Fermi Lab in Batavia IL, 60510, phone: 630-840-3000.
# rev="$Revision: 1603 $$Date: 2023-04-23 20:06:30 -0500 (Sun, 23 Apr 2023) $";

USAGE="\
   usage: `basename $0` [opts] <cmd> [args]...
examples: treset; `basename $0` -M 820 \$TRACE_BIN/trace_cntl test-compare -l150000 4 2 >|merged.txt
          tmodeS 0; treset; `basename $0` -M 820 \$TRACE_BIN/trace_cntl test1 -l500 -d1 >|merged.txt
          # lower loops w/ delay...
          tmodeS 0; treset; `basename $0` -M 820 \$TRACE_BIN/trace_cntl test1 -l500 -d1 >|merged.txt;cat merged.txt|tdelta -d 0 -i #/main: Hi
          tmodeS 0; tonMg debug-debug+2; treset; `basename $0` -M 820 \$TRACE_BIN/trace_cntl test-threads 0 -l500 -d1 -b5 >|merged.txt #/loop=
opts:
-M <hex_mask>  cpu Mask
"
opt_mask=
verbose=0
while getopts hM:xv opt;do
    case $opt in
    x)   set -x;;
    v)   verbose=`expr $verbose + 1`;;
    M)   opt_mask=$OPTARG;;
    ?|h) printf "$USAGE"; exit 2;;
    esac
done
shift $(($OPTIND-1))
test $# -eq 0 && { echo "Wrong number of args: $#. Need 1."; printf "$USAGE"; exit 1; }


vecho() { test $1 -ge $verbose && { shift; echo "$@" 1>&2; }; }



taskset= taskset_mask=
test -n "$opt_mask" && opt_M=-M taskset=taskset taskset_mask=0x$opt_mask
sudo -E trace-cmd record --no-filter -q $opt_M $opt_mask -b 10000 -C x86-tsc -e all  $taskset $taskset_mask "$@"

vecho 1 Now for trace-cmd report...
trace-cmd report -q 2>/dev/null \
| awk 'BEGIN{
  printf("                 tsc     pid cpu            name msg\n");
  printf("-------------------- ------- --- --------------- -------------------------------\n");
 }
 /^cpus=[1-9]/{next}
 {
   nam=gensub(/^ *(.*)-[0-9]* *\[[0-9]*] *[0-9]*: .*/,"\\1",1);
   pid=gensub(/^.*-([0-9]*) *\[[0-9]*] *[0-9]*: .*/,"\\1",1);
   cpu=gensub(/^.*-[0-9]* *\[([0-9]*)] *[0-9]*: .*/,"\\1",1);
   tsc=gensub(/^.*-[0-9]* *\[[0-9]*] *([0-9]*): .*/,"\\1",1);
   rest=gensub(/^.*-[0-9]* *\[[0-9]*] *[0-9]*: (.*)/,"\\1",1);
   printf("%20d %7d %3d %15s %s\n",tsc,pid,cpu,nam,rest)
 }' >|trace-cmd.txt

vecho 1 Now for tshow...
TRACE_SHOW='%x%H%1t %P %C %n %m' trace_cntl show | tac >|trace.txt

vecho 1 Now for sort/merge...
sort -n t*.txt
