#!/bin/sh
# This file (trace_color) was created by Ron Rechenmacher <ron@fnal.gov> on
# Sep 14, 2022. "TERMS AND CONDITIONS" governing this file are in the README
# or COPYING file. If you do not have such a file, one can be obtained by
# contacting Ron or Fermi Lab in Batavia IL, 60510, phone: 630-840-3000.
# $RCSfile: .emacs.gnu,v $
# rev="$Revision: 1.34 $$Date: 2019/04/22 15:23:54 $";


if true;then
tcolor() { : $*=tids
  : build sed filter;: defaults: 1=red 2=green 3=orange 4=blue 5=magenta 6=cyan 7=while 226=yellow ... 
  test -n "${color_nums-}" || color_nums='1 2 3 4 5 6 7 226 93 87 189 195 177';: can put color_nums in env
  num_color_nums=`echo $color_nums | wc -w`
  test $# -eq 0 && { tid_list=`TRACE_SHOW="%x%P" trace_cntl show|awk '{print$1}'|head -300|sort -u | head -n$num_color_nums`; echo found `echo $tid_list | wc -w` unique PIDs in 1st 300 tshow lines >&2; set -- $tid_list; };: at most,could be less
  test $# -eq 0 && { echo need at least 1 tid; return; }
  tid=$1; esc=`printf "\033"`;: no shift to preserver num args to associate with arg with cnum
  filt="s/\( $tid .*$\)/${esc}[38;5;`echo $color_nums|cut -d' ' -f1`m\1${esc}[0m/"
  for num in `seq 2 $#`;do
    tid=$2; shift
    cnum=`echo $color_nums|cut -d' ' -f$num`
    filt="$filt;s/\( $tid .*$\)/${esc}[38;5;${cnum}m\1${esc}[0m/"
  done
  sed -e "$filt"
}
else

tcolor() { : $*=tids
  : build sed filter
  color_nums='31 32 33 34 35 36 37'
  num_color_nums=`echo $color_nums | wc -w`
  test $# -eq 0 && set -- `trace_cntl show|awk '/^ *[0-9]/{print$4}'|head -200|sort -u | head -n$num_color_nums`;: at most,could be less
  test $# -eq 0 && { echo need at least 1 tid; return; }
  tid=$1; shift; esc=`printf "\033"`
  filt="s/\( $tid .*\)/${esc}[31m\1${esc}[0m/";: every nl resets color
  for num in `seq $#`;do
    tid=$1; shift
    cnum=`echo $color_nums|cut -d' ' -f$num`
    filt="$filt;s/\( $tid .*\)/${esc}[${cnum}m\1${esc}[0m/";: every nl resets color
  done
  sed -e "$filt"
}
fi

tcolor "$@"
