#!/bin/sh
 # This file (trace_build) was created by Ron Rechenmacher <ron@fnal.gov> on
 # Jun 14, 2019. "TERMS AND CONDITIONS" governing this file are in the README
 # or COPYING file. If you do not have such a file, one can be obtained by
 # contacting Ron or Fermi Lab in Batavia IL, 60510, phone: 630-840-3000.
 # $RCSfile: .emacs.gnu,v $
 # rev="$Revision: 1.34 $$Date: 2019/04/22 15:23:54 $";

dirnam=`dirname $0`
expr "$dirnam" : / >/dev/null || dirnam=$PWD/$dirnam
srcdir=`dirname $dirnam`
srcdir=`cd $srcdir >/dev/null; pwd`
USAGE="\
   usage: `basename $0` [-i[dir]] <blddir>
examples: `basename $0` trace_build
          `basename $0` -i trace_build # install to first dir in PRODUCTS
          `basename $0` -i\$HOME/p trace_build # install to \$HOME/p
Note: the script determines assumes the source dir to be: $srcdir, and
      buildir should not be within source dir.
"


op1chr='rest=`expr "$op" : "[^-]\(.*\)"`; test -n "$rest" && set -- "-$rest" "$@"'
op1arg='rest=`expr "$op" : "[^-]\(.*\)"`; test -n "$rest" && set -- "$rest"  "$@"'
reqarg="$op1arg;"'test -z "${1+1}" &&echo opt -$op requires arg. &&echo "$USAGE" &&exit'
optlar="$op1arg"' && leq=$rest'
args= do_help= opt_v=0
while [ -n "${1-}" ];do
    if expr "x${1-}" : 'x-' >/dev/null;then
        op=`expr "x$1" : 'x-\(.*\)'`; shift   # done with $1
        leq=`expr "x$op" : 'x-[^=]*\(=\)'` lev=`expr "x$op" : 'x-[^=]*=\(.*\)'`
        test -n "$leq"&&eval "set -- \"\$lev\" \"\$@\""&&op=`expr "x$op" : 'x\([^=]*\)'`
        case "$op" in
        \?*|h*)      eval $op1chr; do_help=1;;
        v*)          eval $op1chr; opt_v=`expr $opt_v + 1`;;
        x*)          eval $op1chr; test $opt_v -ge 1 && set -xv || set -x;;
        i*|-install) eval $optlar;echo rest=$rest; test -n "$leq"&&install=$1&&shift||install=1;;
        *)           echo unknown option -$op$leq$lev; do_help=1;; # see dash_opts5.sh for mix {,un}known
        esac
    else # allow mix of opts and arg (i.e. opts after args)
        aa=`echo "$1" | sed -e "s/'/'\"'\"'/g"` args="$args '$aa'"; shift
    fi
done
eval "set -- $args \"\$@\""; unset args aa
test $# -ne 1 -o -n "$do_help" && { echo "$USAGE"; exit; }
set -u

blddir=$1

expr "$blddir" : / >/dev/null || {
    # readlink -f does not require last dir component to exist
    blddir=`readlink -f $blddir` || { echo parent dir must exist; exit; }
}

expr "$blddir/" : "$srcdir/" >/dev/null && {
    echo Specified blddir seems to be within source dir
    echo srcdir=$srcdir
    echo blddir=$blddir
    exit
}

test -d $blddir || { echo making blddir=$blddir; mkdir $blddir; }

cd "$blddir"

echo srcdir=$srcdir blddir=$blddir

echo "\$PRODUCTS=$PRODUCTS"
if [ -n "${install-}" -a "${install-}" != 1 ];then
    install_dir=$install
else
    install_dir=`echo $PRODUCTS | cut -f1 -d:`
fi
echo install_dir=$install_dir

. $install_dir/setup


latest_rev=`ups list -aKversion cetmodules | sed s/\"//g | tail -1`

setup cetmodules $latest_rev

# may have to specify flavor using -f`ups flavor -4`
latest_cmake=`ups list -aKversion:version cmake \
| sed 's/_\([0-9][^-0-9]\)/_0\1/;s/"//g' | sort | awk '{print$2}' | tail -1`

setup cmake $latest_cmake
# cmake 3.11 or higher required
cmake -DCMAKE_INSTALL_PREFIX=$install_dir \
       -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWANT_UPS:BOOL=ON $srcdir

make -j$(nproc)
make -j$(nproc) package    #install|package
test -n "${install-}" && make -j$(nproc) install
