name: Build Single Pkg Workflow

on:
  push:
    branches: 
      - develop
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:

  build_single_pkg:
    name: build single pkg
    runs-on: ubuntu-latest

    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@main

    - name: change dir permission
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs

    - name: Cache cvmfs cache
      id: cvmfs_cache
      uses: actions/cache@main
      with:
        path: /var/lib/cvmfs/shared
        key: cachecvmfs

    - name: restore dir permission
      run: |
        sudo chown -R cvmfs.cvmfs /var/lib/cvmfs
        sudo chmod -R go-rwx /var/lib/cvmfs

    - name: Checkout pkg
      uses: actions/checkout@main
      with:
        repository: ${{ github.repository }}
        path: scratch/${{ github.repository }}

    - name: run build in docker container with cvmfs bind mount
      run: |
      
        cd $GITHUB_WORKSPACE/scratch
        cat << EOT > build_pkg.sh
        #!/bin/bash
        
        cd /scratch/art-daq
        source /cvmfs/fermilab.opensciencegrid.org/products/artdaq/setup
        
        export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        export buildname="build_\${REPO}"

        mkdir \$buildname
        cd \$buildname

        echo "Logging to /scratch/\$buildname.log"
        echo "Calling source ../\$REPO/ups/setup_for_development || true"
        source ../\$REPO/ups/setup_for_development || exit 1

        echo "Active UPS products:"
        ups active || true
        
        echo "Calling buildtool 2>&1 | tee /scratch/\$buildname.log"
        CETPKG_J=4 buildtool 2>&1 | tee /scratch/\$buildname.log
        exit $?
        EOT
        chmod +x build_pkg.sh

        docker run --rm -v /cvmfs:/cvmfs:shared -v $GITHUB_WORKSPACE/scratch:/scratch eflumerf/sl7-minimal:latest /scratch/build_pkg.sh
    
    - name: Check build log for success
      run: |
        grep "INFO: stage build SUCCESS" ${{ github.workspace }}/scratch/build_*_${{ matrix.build-type }}_${{ matrix.qualifiers }}.log
    
    - name: upload build log file
      uses: actions/upload-artifact@main
      with:
        name: build_log_${{ matrix.build-type }}_${{ matrix.qualifiers }}
        path: ${{ github.workspace }}/scratch/build_*_${{ matrix.build-type }}_${{ matrix.qualifiers }}.log

    - name: change dir permission again
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs
