name: Build Single Pkg Workflow

on:
  push:
    branches: 
      - develop
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:

  build_single_pkg:
    name: build single pkg
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [ 'd', 'p' ]
        qualifiers: [ 's112-e20', 's118-e20', 's118-e26' ]

    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v3

    - name: change dir permission
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs

    - name: Cache cvmfs cache
      id: cvmfs_cache
      uses: actions/cache@v3
      with:
        path: /var/lib/cvmfs/shared
        key: cachecvmfs

    - name: restore dir permission
      run: |
        sudo chown -R cvmfs.cvmfs /var/lib/cvmfs
        sudo chmod -R go-rwx /var/lib/cvmfs

    - name: Checkout pkg
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        path: scratch/${{ github.repository }}

    - name: run build in docker container with cvmfs bind mount
      run: |
      
        cd $GITHUB_WORKSPACE/scratch
        cat << EOT > build_pkg.sh
        #!/bin/bash
        
        cd /scratch/art-daq
        source /cvmfs/fermilab.opensciencegrid.org/products/artdaq/setup || true
        
        export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        export quals=`echo ${{ matrix.qualifiers }}|sed 's/-/:/g'`
        export buildname="build_\${REPO}_${{ matrix.build-type }}_${{ matrix.qualifiers }}"

        mkdir \$buildname
        cd \$buildname

        echo "Logging to /scratch/\$buildname.log"
        echo "Calling source ../\$REPO/ups/setup_for_development -${{ matrix.build-type }} \$quals || true"
        source ../\$REPO/ups/setup_for_development -${{ matrix.build-type }} \$quals || true

        echo "Active UPS products:"
        ups active || true
        
        echo "Calling buildtool 2>&1 | tee /scratch/\$buildname.log"
        CETPKG_J=4 buildtool 2>&1 | tee /scratch/\$buildname.log
        EOT
        chmod +x build_pkg.sh

        docker run --rm -v /cvmfs:/cvmfs:shared -v $GITHUB_WORKSPACE/scratch:/scratch eflumerf/sl7-minimal:latest /scratch/build_pkg.sh

    - name: upload build log file
      uses: actions/upload-artifact@v3
      with:
        name: build_log_${{ matrix.build-type }}_${{ matrix.qualifiers }}
        path: ${{ github.workspace }}/scratch/build_*_${{ matrix.build-type }}_${{ matrix.qualifiers }}.log

    - name: change dir permission again
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs
