name: Test Single Pkg Workflow

on:
  push:
    branches: 
      - develop
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:

  build_single_pkg:
    name: test single pkg
    uses: art-daq/.github/.github/workflows/artdaq-test-single-pkg.yml@stable