name: Test Single Pkg Workflow

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'build type, d or p'
        default: 'd'
      quals:
        description: 'qualifiers'
        default: 's112:e20'

jobs:

  build_single_pkg:
    name: build single pkg
    runs-on: ubuntu-latest

    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v3

    - name: change dir permission
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs

    - name: Cache cvmfs cache
      id: cvmfs_cache
      uses: actions/cache@v3
      with:
        path: /var/lib/cvmfs/shared
        key: cachecvmfs

    - name: restore dir permission
      run: |
        sudo chown -R cvmfs.cvmfs /var/lib/cvmfs
        sudo chmod -R go-rwx /var/lib/cvmfs

    - name: Checkout pkg
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        path: scratch/${{ github.repository }}

    - name: start docker container with bind mount cvmfs
      run: |
      
        export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        cd $GITHUB_WORKSPACE/scratch
        cat << EOT > build_pkg.sh
        #!/bin/bash
        
        cd /scratch/art-daq
        source /cvmfs/fermilab.opensciencegrid.org/products/artdaq/setup || true

        mkdir build_$REPO
        cd build_$REPO
        source ../$REPO/ups/setup_for_development -${{ github.matrix.build-type }} ${{ github.matrix.qualifiers }} || true
        buildtool -t 2>&1 | tee build.log
        EOT
        chmod +x build_pkg.sh

        docker run --rm -v /cvmfs:/cvmfs:shared -v $GITHUB_WORKSPACE/scratch:/scratch eflumerf/sl7-minimal:latest /scratch/build_pkg.sh

    - name: upload build log file
      uses: actions/upload-artifact@v3
      with:
        name: build_log_${{ matrix.os_name }}
        path: ${{ github.workspace }}/scratch/build_*/build.log

    - name: change dir permission again
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs
